baseurl = "http://adiiram_journal.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Adii's Journal"
theme = "minimal"

[params]
    author = "Adii Ram"
    description = "My learnings over the years"
    githubUsername = "#"
    accent = "#fe4a49"
    showBorder = true
    backgroundColor = "#faf0e6"
    font = "Montserrat" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["python","bash"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2